/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    CommentSection: typeof import('./components/CommentSection.vue')['default']
    DeletePostConfirmation: typeof import('./components/DeletePostConfirmation.vue')['default']
    FilterPost: typeof import('./components/FilterPost.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PostAction: typeof import('./components/PostAction.vue')['default']
    PostCard: typeof import('./components/PostCard.vue')['default']
    PostForm: typeof import('./components/PostForm.vue')['default']
    ProfileAbout: typeof import('./components/ProfileAbout.vue')['default']
    ProfileEditDialog: typeof import('./components/ProfileEditDialog.vue')['default']
    RecommendationSidebar: typeof import('./components/RecommendationSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./components/SearchResult.vue')['default']
    ShareModal: typeof import('./components/ShareModal.vue')['default']
    UserButton: typeof import('./components/UserButton.vue')['default']
  }
}
